// var json = [
// {"schema":
//  [{"position":2,"name":"host","type":"string"},{"position": 3,"name":"path","type":"string"},{"position": 4,"name":"user_agent","type":"string"},{"position": 6,"name":"cookie","type":"string"},{"position": 7,"name":"subdomain","type":"string"},{"position": 8,"name":"is_admin","type":"bool"},{"position": 9,"name":"is_member","type":"bool"},{"position": 10,"name":"is_owner","type":"bool"},{"position": 12,"name":"request_method","type":"string"},{"position": 13,"name":"screen_name","type":"string"},{"position": 14,"name":"trace","type":"string"}],"name":"BazelClientPerformance"}, {"schema":[{"position":19,"name":"referrer","type":"string"}, {"position": 20,"name":"reload_count","type":"i16"}],"name":"BasicFlows"},{"schema": [{"position":16,"name":"reload_count","type":"i16"},{"position": 15 ,"name":"referrer","type":"string"}],"name":"BazelClientPerformance"}, {"schema":[{"position":14,"name":"referrer","type":"string"}, {"position": 15,"name":"reload_count","type":"i16"}],"name":"EmailVerification"}, {"schema":[{"position":19,"name":"reload_count","type":"i16"}, {"position":18,"name":"referrer","type":"string"}],"name":"GYO"}, {"schema":[{"position":19,"name":"referrer","type":"string"}, {"position":20,"name":"reload_count","type":"i16"}],"name":"Homepage"}, {"schema":[{"position":21,"name":"referrer","type":"string"}, {"position": 27,"name":"num_sent","type":"i32"}],"name":"InvitationEvent"}, {"schema":[{"position":14,"name":"referrer","type":"string"}, {"position":15,"name":"reload_count","type":"i16"}],"name":"PageView"}, {"schema":[{"position":2,"name":"env","type":"string"},{"position": 3,"name":"load_signin_page_exec_time_seconds","type":"double"}, {"position":4,"name":"load_signin_page_test_passed","type":"bool"}, {"position":5,"name":"sign_in_exec_time_seconds","type":"double"}, {"position":6,"name":"sign_in_test_passed","type":"bool"}],
//  "name":"bfm- pretzel"},
// {"schema":
//  [{"position": 24,"name":"email_count","type":"i16"}],
//  "name":"InvitationEvent"}];
//  
 
 var json = [{"schema":[{"position":2,"name":"host","type":"string"},{"position": 3,"name":"path","type":"string"},{"position": 4,"name":"user_agent","type":"string"},{"position": 6,"name":"cookie","type":"string"},{"position": 7,"name":"subdomain","type":"string"},{"position": 8,"name":"is_admin","type":"bool"},{"position": 9,"name":"is_member","type":"bool"},{"position": 10,"name":"is_owner","type":"bool"},{"position": 12,"name":"request_method","type":"string"},{"position": 13,"name":"screen_name","type":"string"},{"position": 14,"name":"trace","type":"string"}],"name":"BazelClientPerformance"}, {"schema":[{"position":19,"name":"referrer","type":"string"}, {"position": 20,"name":"reload_count","type":"i16"}],"name":"BasicFlows"}]